###GET all books
GET http://localhost:3000/api/books HTTP/1.1

###GET a single book
GET http://localhost:3000/api/books/9783257228007 HTTP/1.1

###GET a single book that does not exist
GET http://localhost:3000/api/books/asinglebook HTTP/1.1

###POST a single book
POST http://localhost:3000/api/books/9783608939842
Content-Type: application/json

    {
      "title": "Der Herr der Ringe",
      "author": "John R. R. Tolkien",
      "originaltitle": "The Lord of the Rings",
      "release": "1954-1955",
      "genre": "Fantasy",
      "ISBN": "9783608939842",
      "cover": "https://www.klett-cotta.de/media/1/9783608939842.jpg"
    } 

###POST a bookchart
POST http://localhost:3000/api/books HTTP/1.1
Content-Type: application/json

    {
      "title": "Der Herr der Ringe",
      "author": "John R. R. Tolkien",
      "originaltitle": "The Lord of the Rings",
      "release": "1954-1955",
      "genre": "Fantasy",
      "ISBN": "9783608939842",
      "cover": "https://www.klett-cotta.de/media/1/9783608939842.jpg"
    } 


###DELETE a book
DELETE http://localhost:3000/api/books/9783608939842 HTTP/1.1

###PATCh a new parameter to an object
PATCh   http://localhost:3000/api/books/9783730602294 HTTP/1.1
Content-Type: application/json

{
    "summary": "some text to update"
}